# Generated by Django 4.1.3 on 2022-12-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_planner', '0004_board_expiring_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='expiring_date',
        ),
        migrations.AddField(
            model_name='card',
            name='expiring_date',
            field=models.DateTimeField(null=True),
        ),
    ]
